"""
Add remaining game translations (Tamagoshi, Pesadelo, JackCandy, LDI, ArenaTatics)
"""
import json, os

ROOT = r"C:\Users\isaia\Downloads\BRANDS\Lutas de Ilusão\SiteLDI"
I18N = os.path.join(ROOT, "src", "i18n")

def load_json(path):
    with open(path, "r", encoding="utf-8") as f: return json.load(f)
def save_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False); f.write("\n")

pt = load_json(os.path.join(I18N, "pt.json"))
en = load_json(os.path.join(I18N, "en.json"))
es = load_json(os.path.join(I18N, "es.json"))

G = {}  # {lang: {game: {key: val}}}

G["pt"] = {
  "tamagoshi": {
    "alimentar": "alimentar", "banhar": "banhar", "passear": "passear",
    "brincar": "brincar", "loja": "loja", "voltar": "voltar",
    "fome": "🍖 Fome", "higiene": "🧼 Higiene", "energia": "⚡ Energia",
    "humor": "🎭 Humor", "dix_infinito": "🪙 ∞ DIX",
    "iniciar_passeio": "INICIAR", "fim_passeio": "FIM DE PASSEIO",
    "jogar_novamente": "JOGAR DE NOVO", "desistir": "desistir",
    "pista": "pista {a}/{b}", "moedas": "moedas: {n}",
    "ovo_tocar": "tocar no ovo", "ovo_texto": "um ovo misterioso... algo se mexe lá dentro",
    "voltar_extras": "voltar aos extras", "slot_vazio": "vazio",
    "novo_jogo": "novo jogo", "admin": "admin",
    "fast_off": "fast: off", "trocar": "trocar",
    "ultimos_resultados": "ultimos resultados:",
    "coletadas": "⭐ {n} coletadas",
    "partida_titulo": "PARTIDA",
    "luto_titulo": "LUTO",
    "loja_titulo": "LOJA",
    "selecao_titulo": "ESCOLHA SUA CRIATURA",
    "selecao_sub": "Escolha sabiamente. Sua jornada começa agora.",
    "sem_fichas": "SEM FICHAS",
  },
  "pesadelo": {
    "titulo": "PRESADELO PARTICULAR",
    "subtitulo": "20 casos. uma conspiração. um amigo em perigo.",
    "iniciar": "INICIAR",
    "continuar": "CONTINUAR",
    "novo_jogo": "NOVO JOGO",
    "carregando": "CARREGANDO...",
    "caso": "CASO {n}",
    "sucesso": "SUCESSO",
    "falhou": "FALHOU",
    "pistas": "PISTAS",
    "interrogar": "INTERROGAR",
    "investigar": "INVESTIGAR",
    "concluir": "CONCLUIR",
    "voltar": "VOLTAR",
    "proximo": "PRÓXIMO",
    "prova": "PROVA",
    "culpado": "CULPADO",
    "inocente": "INOCENTE",
    "relatorio": "RELATÓRIO",
  },
  "jackcandy": {
    "titulo": "JACK DREAM BEER",
    "subtitulo": "o sonho não tem regras. mas tem cerveja.",
    "slot_vazio": "vazio",
    "novo_jogo": "novo jogo",
    "continuar": "CONTINUAR",
    "apagar": "APAGAR",
    "voltar": "VOLTAR",
    "inventario": "INVENTÁRIO",
    "diario": "DIÁRIO",
    "mapa": "MAPA",
    "explorar": "EXPLORAR",
    "descansar": "DESCANSAR",
    "investigar": "INVESTIGAR",
    "dialogar": "DIALOGAR",
    "avançar": "AVANÇAR",
    "coletar": "COLETAR",
    "usar": "USAR",
    "examinar": "EXAMINAR",
    "falar": "FALAR",
    "atacar": "ATACAR",
    "defender": "DEFENDER",
    "fugir": "FUGIR",
    "proximo": "PRÓXIMO",
    "pular": "PULAR",
  },
  "ldi": {
    "titulo": "LDI LENDAS",
    "entrar": "INSERIR FICHA",
    "novo_jogo": "NOVO JOGO",
    "continuar": "CONTINUAR",
    "criar_personagem": "CRIAR PERSONAGEM",
    "voltar": "VOLTAR",
    "inventario": "INVENTÁRIO",
    "personagem": "PERSONAGEM",
    "combate": "COMBATE",
    "vitoria": "VITÓRIA",
    "derrota": "DERROTA",
    "fugir": "FUGIR",
    "atacar": "ATACAR",
    "defender": "DEFENDER",
    "habilidade": "HABILIDADE",
    "item": "ITEM",
    "dialogo": "DIÁLOGO",
    "pista": "PISTA",
    "caderno": "CADERNO DE PISTAS",
    "proximo": "PRÓXIMO",
    "pular": "PULAR",
    "confirmar": "CONFIRMAR",
    "selecionar": "SELECIONAR",
    "atributos": "ATRIBUTOS",
    "pericias": "PERÍCIAS",
    "vantagens": "VANTAGENS",
    "desvantagens": "DESVANTAGENS",
  },
  "tatics": {
    "loading": "CARREGANDO SISTEMA...",
    "erro_login": "Faça login para acessar o sistema",
    "voltar": "VOLTAR",
    "menu_principal": "MENU PRINCIPAL",
    "continuar": "CONTINUAR",
    "novo_jogo": "NOVO JOGO",
    "selecionar_time": "SELECIONAR TIME",
    "iniciar_batalha": "INICIAR BATALHA",
    "vitoria": "VITÓRIA",
    "derrota": "DERROTA",
    "pre_batalha": "PRÉ-BATALHA",
    "seu_time": "SEU TIME",
    "inimigos": "INIMIGOS",
    "vs": "⚔️ VS ⚔️",
    "nivel": "Nv.",
    "tier": "Tier",
    "confirmar": "CONFIRMAR",
  },
}

G["en"] = {
  "tamagoshi": {
    "alimentar": "feed", "banhar": "bathe", "passear": "walk",
    "brincar": "play", "loja": "shop", "voltar": "back",
    "fome": "🍖 Hunger", "higiene": "🧼 Hygiene", "energia": "⚡ Energy",
    "humor": "🎭 Mood", "dix_infinito": "🪙 ∞ DIX",
    "iniciar_passeio": "START", "fim_passeio": "WALK OVER",
    "jogar_novamente": "PLAY AGAIN", "desistir": "give up",
    "pista": "stage {a}/{b}", "moedas": "coins: {n}",
    "ovo_tocar": "touch the egg", "ovo_texto": "a mysterious egg... something moves inside",
    "voltar_extras": "back to extras", "slot_vazio": "empty",
    "novo_jogo": "new game", "admin": "admin",
    "fast_off": "fast: off", "trocar": "swap",
    "ultimos_resultados": "last results:",
    "coletadas": "⭐ {n} collected",
    "partida_titulo": "DEPARTURE",
    "luto_titulo": "MOURNING",
    "loja_titulo": "SHOP",
    "selecao_titulo": "CHOOSE YOUR CREATURE",
    "selecao_sub": "Choose wisely. Your journey begins now.",
    "sem_fichas": "NO TOKENS",
  },
  "pesadelo": {
    "titulo": "PARTICULAR NIGHTMARE",
    "subtitulo": "20 cases. a conspiracy. a friend in danger.",
    "iniciar": "START", "continuar": "CONTINUE",
    "novo_jogo": "NEW GAME", "carregando": "LOADING...",
    "caso": "CASE {n}", "sucesso": "SUCCESS", "falhou": "FAILED",
    "pistas": "CLUES", "interrogar": "INTERROGATE",
    "investigar": "INVESTIGATE", "concluir": "CONCLUDE",
    "voltar": "BACK", "proximo": "NEXT",
    "prova": "EVIDENCE", "culpado": "GUILTY",
    "inocente": "INNOCENT", "relatorio": "REPORT",
  },
  "jackcandy": {
    "titulo": "JACK DREAM BEER",
    "subtitulo": "dreams have no rules. but they have beer.",
    "slot_vazio": "empty", "novo_jogo": "new game",
    "continuar": "CONTINUE", "apagar": "DELETE",
    "voltar": "BACK", "inventario": "INVENTORY",
    "diario": "JOURNAL", "mapa": "MAP",
    "explorar": "EXPLORE", "descansar": "REST",
    "investigar": "INVESTIGATE", "dialogar": "TALK",
    "avançar": "ADVANCE", "coletar": "COLLECT",
    "usar": "USE", "examinar": "EXAMINE",
    "falar": "SPEAK", "atacar": "ATTACK",
    "defender": "DEFEND", "fugir": "FLEE",
    "proximo": "NEXT", "pular": "SKIP",
  },
  "ldi": {
    "titulo": "LDI LEGENDS",
    "entrar": "INSERT TOKEN", "novo_jogo": "NEW GAME",
    "continuar": "CONTINUE", "criar_personagem": "CREATE CHARACTER",
    "voltar": "BACK", "inventario": "INVENTORY",
    "personagem": "CHARACTER", "combate": "COMBAT",
    "vitoria": "VICTORY", "derrota": "DEFEAT",
    "fugir": "FLEE", "atacar": "ATTACK",
    "defender": "DEFEND", "habilidade": "ABILITY",
    "item": "ITEM", "dialogo": "DIALOG",
    "pista": "CLUE", "caderno": "CLUE NOTEBOOK",
    "proximo": "NEXT", "pular": "SKIP",
    "confirmar": "CONFIRM", "selecionar": "SELECT",
    "atributos": "ATTRIBUTES", "pericias": "SKILLS",
    "vantagens": "ADVANTAGES", "desvantagens": "DISADVANTAGES",
  },
  "tatics": {
    "loading": "LOADING SYSTEM...",
    "erro_login": "Please log in to access the system",
    "voltar": "BACK", "menu_principal": "MAIN MENU",
    "continuar": "CONTINUE", "novo_jogo": "NEW GAME",
    "selecionar_time": "SELECT TEAM", "iniciar_batalha": "START BATTLE",
    "vitoria": "VICTORY", "derrota": "DEFEAT",
    "pre_batalha": "PRE-BATTLE", "seu_time": "YOUR TEAM",
    "inimigos": "ENEMIES", "vs": "⚔️ VS ⚔️",
    "nivel": "Lv.", "tier": "Tier",
    "confirmar": "CONFIRM",
  },
}

G["es"] = {
  "tamagoshi": {
    "alimentar": "alimentar", "banhar": "bañar", "passear": "pasear",
    "brincar": "jugar", "loja": "tienda", "voltar": "volver",
    "fome": "🍖 Hambre", "higiene": "🧼 Higiene", "energia": "⚡ Energía",
    "humor": "🎭 Humor", "dix_infinito": "🪙 ∞ DIX",
    "iniciar_passeio": "INICIAR", "fim_passeio": "FIN DEL PASEO",
    "jogar_novamente": "JUGAR DE NUEVO", "desistir": "rendirse",
    "pista": "pista {a}/{b}", "moedas": "monedas: {n}",
    "ovo_tocar": "tocar el huevo", "ovo_texto": "un huevo misterioso... algo se mueve dentro",
    "voltar_extras": "volver a extras", "slot_vazio": "vacío",
    "novo_jogo": "nuevo juego", "admin": "admin",
    "fast_off": "fast: off", "trocar": "cambiar",
    "ultimos_resultados": "últimos resultados:",
    "coletadas": "⭐ {n} recolectadas",
    "partida_titulo": "PARTIDA",
    "luto_titulo": "LUTO",
    "loja_titulo": "TIENDA",
    "selecao_titulo": "ELIGE TU CRIATURA",
    "selecao_sub": "Elige sabiamente. Tu viaje comienza ahora.",
    "sem_fichas": "SIN FICHAS",
  },
  "pesadelo": {
    "titulo": "PESADILLA PARTICULAR",
    "subtitulo": "20 casos. una conspiración. un amigo en peligro.",
    "iniciar": "INICIAR", "continuar": "CONTINUAR",
    "novo_jogo": "NUEVO JUEGO", "carregando": "CARGANDO...",
    "caso": "CASO {n}", "sucesso": "ÉXITO", "falhou": "FALLÓ",
    "pistas": "PISTAS", "interrogar": "INTERROGAR",
    "investigar": "INVESTIGAR", "concluir": "CONCLUIR",
    "voltar": "VOLVER", "proximo": "SIGUIENTE",
    "prova": "PRUEBA", "culpado": "CULPABLE",
    "inocente": "INOCENTE", "relatorio": "INFORME",
  },
  "jackcandy": {
    "titulo": "JACK DREAM BEER",
    "subtitulo": "el sueño no tiene reglas. pero tiene cerveza.",
    "slot_vazio": "vacío", "novo_jogo": "nuevo juego",
    "continuar": "CONTINUAR", "apagar": "BORRAR",
    "voltar": "VOLVER", "inventario": "INVENTARIO",
    "diario": "DIARIO", "mapa": "MAPA",
    "explorar": "EXPLORAR", "descansar": "DESCANSAR",
    "investigar": "INVESTIGAR", "dialogar": "DIALOGAR",
    "avançar": "AVANZAR", "coletar": "RECOLECTAR",
    "usar": "USAR", "examinar": "EXAMINAR",
    "falar": "HABLAR", "atacar": "ATACAR",
    "defender": "DEFENDER", "fugir": "HUIR",
    "proximo": "SIGUIENTE", "pular": "SALTAR",
  },
  "ldi": {
    "titulo": "LDI LEYENDAS",
    "entrar": "INSERTAR FICHA", "novo_jogo": "NUEVO JUEGO",
    "continuar": "CONTINUAR", "criar_personagem": "CREAR PERSONAJE",
    "voltar": "VOLVER", "inventario": "INVENTARIO",
    "personagem": "PERSONAJE", "combate": "COMBATE",
    "vitoria": "VICTORIA", "derrota": "DERROTA",
    "fugir": "HUIR", "atacar": "ATACAR",
    "defender": "DEFENDER", "habilidade": "HABILIDAD",
    "item": "OBJETO", "dialogo": "DIÁLOGO",
    "pista": "PISTA", "caderno": "CUADERNO DE PISTAS",
    "proximo": "SIGUIENTE", "pular": "SALTAR",
    "confirmar": "CONFIRMAR", "selecionar": "SELECCIONAR",
    "atributos": "ATRIBUTOS", "pericias": "PERICIAS",
    "vantagens": "VENTAJAS", "desvantagens": "DESVENTAJAS",
  },
  "tatics": {
    "loading": "CARGANDO SISTEMA...",
    "erro_login": "Inicia sesión para acceder al sistema",
    "voltar": "VOLVER", "menu_principal": "MENÚ PRINCIPAL",
    "continuar": "CONTINUAR", "novo_jogo": "NUEVO JUEGO",
    "selecionar_time": "SELECCIONAR EQUIPO",
    "iniciar_batalha": "INICIAR BATALLA",
    "vitoria": "VICTORIA", "derrota": "DERROTA",
    "pre_batalha": "PRE-BATALLA", "seu_time": "TU EQUIPO",
    "inimigos": "ENEMIGOS", "vs": "⚔️ VS ⚔️",
    "nivel": "Nv.", "tier": "Tier",
    "confirmar": "CONFIRMAR",
  },
}

for lang in ["pt", "en", "es"]:
    d = load_json(os.path.join(I18N, f"{lang}.json"))
    # Merge new games into existing games
    if "games" not in d: d["games"] = {}
    for game, data in G[lang].items():
        if game not in d["games"]: d["games"][game] = {}
        d["games"][game].update(data)
    save_json(os.path.join(I18N, f"{lang}.json"), d)
    total = sum(len(v) for v in d["games"].values() if isinstance(v, dict))
    print(f"✅ {lang}.json: {len(d['games'])} games, ~{total} total keys")
