export const EFFECTS_MAP = {
  dano: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 800,
    prioridade: 1,
    primitivo: 'TextoEffect',
    params: {
      cor: '#ffffff',
      particula: null,
      tamanho: 1.2,
      velocidade: 'rapida',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  flash: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 400,
    prioridade: 1,
    primitivo: 'FlashEffect',
    params: {
      cor: '#ff0000',
      particula: null,
      tamanho: 1.0,
      velocidade: 'rapida',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  shake: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 500,
    prioridade: 1,
    primitivo: 'ShakeEffect',
    params: {
      cor: null,
      particula: null,
      tamanho: 1.0,
      velocidade: 'rapida',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  balao: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 1300,
    prioridade: 2,
    primitivo: 'TextoEffect',
    params: {
      cor: '#ffcc00',
      particula: null,
      tamanho: 0.9,
      velocidade: 'lenta',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  popup: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 800,
    prioridade: 1,
    primitivo: 'TextoEffect',
    params: {
      cor: '#ffffff',
      particula: null,
      tamanho: 1.5,
      velocidade: 'rapida',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  banner_ia: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 1500,
    prioridade: 1,
    primitivo: 'TextoEffect',
    params: {
      cor: '#ff4444',
      particula: null,
      tamanho: 1.2,
      velocidade: 'normal',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  anuncio_turno: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 2000,
    prioridade: 0,
    primitivo: 'TextoEffect',
    params: {
      cor: '#ffffff',
      particula: null,
      tamanho: 1.8,
      velocidade: 'lenta',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  trail: {
    canal: 'canvas',
    duracao_auto: true,
    duracao: 500,
    prioridade: 1,
    primitivo: 'TrailEffect',
    params: {
      cor: '#8888ff',
      particula: null,
      tamanho: 0.5,
      velocidade: 'normal',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  melee: {
    canal: 'canvas',
    duracao_auto: true,
    duracao: 500,
    prioridade: 1,
    primitivo: 'AuraEffect',
    params: {
      cor: '#ff8800',
      particula: 'fogo',
      tamanho: 1.0,
      velocidade: 'rapida',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  projetil: {
    canal: 'canvas',
    duracao_auto: true,
    duracao: 600,
    prioridade: 1,
    primitivo: 'ProjetilEffect',
    params: {
      cor: '#ffaa00',
      particula: null,
      tamanho: 0.8,
      velocidade: 'normal',
      som: null,
      impactoAoChegar: 'ImpactoEffect',
      impactoParams: { cor: '#ffaa00', raio: 1.0 },
    },
  },
  ia_thinking: {
    canal: 'hud',
    duracao_auto: false,
    duracaoPorTurno: 3000,
    prioridade: 1,
    primitivo: 'TextoEffect',
    params: {
      cor: '#aaaaaa',
      particula: null,
      tamanho: 0.8,
      velocidade: 'lenta',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  vitoria: {
    canal: 'overlay',
    duracao_auto: true,
    duracao: 3000,
    prioridade: 0,
    primitivo: 'TextoEffect',
    params: {
      cor: '#ffd700',
      particula: null,
      tamanho: 2.0,
      velocidade: 'lenta',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  hp_delta: {
    canal: 'hud',
    duracao_auto: true,
    duracao: 600,
    prioridade: 1,
    primitivo: 'AuraEffect',
    params: {
      cor: '#ff4444',
      particula: null,
      tamanho: 1.0,
      velocidade: 'lenta',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  bola_de_fogo: {
    canal: 'canvas',
    duracao_auto: true,
    duracao: 600,
    primitivo: 'ProjetilEffect',
    params: {
      cor: '#ff4400',
      particula: 'fogo',
      tamanho: 1.0,
      velocidade: 'normal',
      som: null,
      impactoAoChegar: 'ImpactoEffect',
      impactoParams: { cor: '#ff4400', raio: 1.5 },
    },
  },
  bola_de_gelo: {
    canal: 'canvas',
    duracao_auto: true,
    duracao: 600,
    primitivo: 'ProjetilEffect',
    params: {
      cor: '#00aaff',
      particula: 'gelo',
      tamanho: 1.0,
      velocidade: 'normal',
      som: null,
      impactoAoChegar: 'ImpactoEffect',
      impactoParams: { cor: '#00aaff', raio: 1.5 },
    },
  },
  veneno: {
    canal: 'overlay',
    duracao_auto: false,
    duracaoPorTurno: 600,
    prioridade: 1,
    primitivo: 'StatusEffect',
    params: {
      cor: '#44ff00',
      particula: 'veneno',
      tamanho: 0.8,
      velocidade: 'lenta',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  highlight_movimento: {
    canal: 'canvas',
    duracao_auto: false,
    prioridade: 0,
    primitivo: 'HighlightEffect',
    params: {
      cor: '#00eeff',
      alpha: 0.06,
      tipo: 'movimento',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  highlight_ataque: {
    canal: 'canvas',
    duracao_auto: false,
    prioridade: 0,
    primitivo: 'HighlightEffect',
    params: {
      cor: '#ff2244',
      alpha: 0.08,
      tipo: 'ataque',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  highlight_range: {
    canal: 'canvas',
    duracao_auto: false,
    prioridade: 0,
    primitivo: 'HighlightEffect',
    params: {
      cor: '#ffcc00',
      alpha: 0.05,
      tipo: 'alcance',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
  highlight_limpar: {
    canal: 'canvas',
    duracao_auto: true,
    duracao: 1,
    prioridade: 99,
    primitivo: 'HighlightEffect',
    params: {
      cor: null,
      alpha: 0,
      tipo: 'limpar',
      som: null,
      impactoAoChegar: null,
      impactoParams: null,
    },
  },
}
