-- Migration 017: (vazia) — não é mais necessário adicionar coluna 'saude'
-- O sistema timestamp-only calcula as barras localmente via localStorage + decaimento.
-- saveToCloud não envia mais valores de barra (fome, higiene, energia, humor, saude).
-- loadFromCloud usa data.saude ?? 100 (default se coluna não existir).
-- A coluna saude não precisa existir no Supabase.
